export const DEFAULT_INGREDIENTS = [
  {
    _id: '692889f16bf770001bfeb4cc',
    name: 'Краторная булка N-200i',
    type: 'bun',
    price: 1255,
    image: 'https://code.s3.yandex.net/react/code/bun-02.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/bun-02-large.png',
    calories: 420,
    proteins: 80,
    fat: 24,
    carbohydrates: 53,
  },
  {
    _id: '692889f16bf770001bfeb4d4',
    name: 'Соус традиционный галактический',
    type: 'sauce',
    price: 15,
    image: 'https://code.s3.yandex.net/react/code/sauce-03.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/sauce-03-large.png',
    calories: 99,
    proteins: 42,
    fat: 24,
    carbohydrates: 42,
  },
  {
    _id: '692889f16bf770001bfeb4cf',
    name: 'Мясо бессмертных моллюсков Protostomia',
    type: 'main',
    price: 1337,
    image: 'https://code.s3.yandex.net/react/code/meat-02.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/meat-02-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/meat-02-large.png',
    calories: 420,
    proteins: 433,
    fat: 244,
    carbohydrates: 33,
  },
  {
    _id: '692889f16bf770001bfeb4d7',
    name: 'Плоды Фалленианского дерева',
    type: 'main',
    price: 874,
    image: 'https://code.s3.yandex.net/react/code/sp_1.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/sp_1-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/sp_1-large.png',
    calories: 77,
    proteins: 20,
    fat: 5,
    carbohydrates: 55,
  },
  {
    _id: '692889f16bf770001bfeb4d6',
    name: 'Хрустящие минеральные кольца',
    type: 'main',
    price: 300,
    image: 'https://code.s3.yandex.net/react/code/mineral_rings.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/mineral_rings-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/mineral_rings-large.png',
    calories: 986,
    proteins: 808,
    fat: 689,
    carbohydrates: 609,
  },

  {
    _id: '692889f16bf770001bfeb4d6',
    name: 'Хрустящие минеральные кольца',
    type: 'main',
    price: 300,
    image: 'https://code.s3.yandex.net/react/code/mineral_rings.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/mineral_rings-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/mineral_rings-large.png',
    calories: 986,
    proteins: 808,
    fat: 689,
    carbohydrates: 609,
  },
  {
    _id: '692889f16bf770001bfeb4cd',
    name: 'Флюоресцентная булка R2-D3',
    type: 'bun',
    price: 988,
    image: 'https://code.s3.yandex.net/react/code/bun-01.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/bun-01-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/bun-01-large.png',
    calories: 643,
    proteins: 44,
    fat: 26,
    carbohydrates: 85,
  },
];
